format = """
$directory\
$conda\
$git_branch\
$package\
$cmd_duration\
$character\
"""

[directory]
read_only = " "

[directory.substitutions]
#"Documents" =  "Documents  "
#"Downloads" = "Downloads  "
#"Music" = "Music  "
##"Pictures" = "Pictures  "


[character]


[cmd_duration]
min_time = 500
show_milliseconds = false
disabled = true
format = " 🕙 $duration($style) "
style = "bold italic #87A752"


[sudo]
style = "bold green"
symbol = "👩‍💻 "
disabled = false

[git_branch]

[conda]
format = "[$environment](dimmed green) "







[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

